

version: '3.8'

services:
  # The NestJS Application Service
  app:
    build: .
    container_name: booking_app
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: booking_db
    depends_on:
      db:
        # This is the key change. The app will now wait for the db
        # service to report that it is 'healthy'.
        condition: service_healthy

  # The PostgreSQL Database Service
  db:
    image: postgres:14-alpine
    container_name: booking_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: booking_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # This healthcheck command periodically checks if the PostgreSQL
    # server is ready to accept commands.
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d booking_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
